name: Deploy Fake
on: 
    workflow_call: 
        secrets:
            ambiente:
                required: true
                description: "Ambiente que vai ser feito o deploy"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: "curl -X POST https://webhook.site/#!/view/2c5fe285-b947-4750-bb12-029abb381004/8cb7fced-2ac0-48a9-a576-112867ebc767/1 -d '{ ambiente: ${{ secrets.ambiente }}}'"