name: Deploy Fake
on: 
    workflow_call: 
        secrets:
            ambiente:
                required: true
                description: "Ambiente que vai ser feito o deploy"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ secrets.ambiente }}"